#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# LogicWard — Raspberry Pi first-time bootstrap.
# Run ONCE on the Pi after cloning the repo.
#
#   git clone https://github.com/positromen/Adani-Project.git
#   cd Adani-Project
#   bash deploy/pi_bootstrap.sh <LAPTOP_LAN_IP>
#
# <LAPTOP_LAN_IP> is the laptop running the SOC dashboard (e.g. 192.168.1.50).
# Raspberry Pi OS (Bookworm) blocks system pip (PEP 668), so we use a venv.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

LAPTOP_IP="${1:-${LOGICWARD_LAPTOP_IP:-}}"
IFACE="${2:-wlan0}"                       # this Pi is on Wi-Fi -> wlan0
TOKEN="${LOGICWARD_TOKEN:-logicward-dev-token-change-me}"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

if [ -z "$LAPTOP_IP" ]; then
  echo "ERROR: pass the laptop's LAN IP, e.g.:  bash deploy/pi_bootstrap.sh 192.168.1.50"
  echo "       (find it on the laptop with 'ipconfig'; both devices must be on Wi-Fi 'Noone')"
  exit 1
fi

echo "[1/4] apt packages (python venv, git)…"
sudo apt-get update -y
sudo apt-get install -y python3-venv python3-pip git

echo "[2/4] Python virtualenv + dependencies…"
python3 -m venv .venv
# shellcheck disable=SC1091
. .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip install "scapy>=2.5" "gpiozero>=2.0"   # Pi hardware sensors (arp_watch, gpio_tamper)

echo "[3/4] Writing deploy/pi.env…"
cat > deploy/pi.env <<EOF
# Generated by pi_bootstrap.sh — edit LAPTOP_IP/TOKEN here if they change.
export LOGICWARD_INGEST_URL="http://${LAPTOP_IP}:8080/api/ingest"
export LOGICWARD_TOKEN="${TOKEN}"
export LOGICWARD_IFACE="${IFACE}"
EOF
cat deploy/pi.env

echo "[4/4] Done."
echo "   Start the PLC + agent with:   bash deploy/run_pi.sh"
echo "   (the laptop must run:          deploy\\run_laptop.ps1 <pi-ip-or-hostname>)"
